FROM python

EXPOSE 80

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

# ENTRYPOINT [ "python" ]
# CMD [ "app.py" ]
CMD ["gunicorn", "--conf", "gunicorn_conf.py", "--bind", "0.0.0.0:80", "app:app"]